name: color_palette_app
description: The Color Palette App is a Flutter application that allows users to select an image and extract color palettes from the image. Users can then view and interact with the generated color palettes.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  palette_generator: ^0.3.3+2
  image_picker: ^0.8.7+5
  share: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-Italic.ttf
          style: italic
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-Regular.ttf
        - asset: assets/fonts/Cinzel-Bold.ttf
          weight: 700

  # You can remove the flutter_image_picker and color_thief_flutter dependencies
  # if you don't want to use them.
